### ISSUE TITLE
There is a bug

### ISSUE THREAD

**Issue by chinlee1523** [nlp-compromise/nlp_compromise#1016]
When I execute this code:
`import nlp from 'compromise'

let doc = nlp('she sells seashells by the seashore.')
doc.verbs().toPastTense()
doc.text()`

There is an error :
[Nest] 31129  - 2023/05/26 16:23:26   ERROR [ExceptionsHandler] (0 , compromise_1.default) is not a function
TypeError: (0 , compromise_1.default) is not a function

**Comment by b1n1yam** [comment]
Facing the same issue. I am doing `const nlp = require ('compromise');` to get around the error
