### ISSUE TITLE
Part-of-speech tagging broken

### ISSUE THREAD

**Issue by Glassig** [nlp-compromise/nlp_compromise#102]
Hi,

I played around a bit with your part-of-speech tagging that is here: http://nlp-compromise.github.io/website/, and it kind of doesn't work. For example:
"move that chair to the table" is identified as "noun determiner noun preposition determiner adjective" when it should be "verb _ _ _ _ noun".

**Comment by spencermountain** [comment]
ah, thanks.
"table" got caught on a sloppy  ".able" regex.. as in, "workable, singable, walkable.."
thanks, will fix.
please let me know other issues you find
cheers

**Comment by Glassig** [comment]
Okay, but "move" is still defined as a noun.

**Comment by spencermountain** [comment]
yeah, you're right. maybe something is up. i did a release yesterday that touched these rules.
i'm gonna look at more full tests to spot these issues. Lots of work is needed

**Comment by Glassig** [comment]
Oh, another thing; it could be worth it if there are more nouns that hit that wall. Like, cable, stable, fable and so forth

**Comment by spencermountain** [comment]
hey Angelina, think I got this working in `v6.2.1`
```javascript
nlp.sentence('table is moveable').terms
// Noun, Verb, Adjective
```
this was a good one. cheers

**Comment by Glassig** [comment]
Good work! Glad I could help :D
