### ISSUE TITLE
nlp.text() breaking with certain inputs

### ISSUE THREAD

**Issue by tsadykhov** [nlp-compromise/nlp_compromise#103]
You can recreate this on the demo site by putting the following into the Part-of-Speech tagging section: _"Come experience the energy and electricity of the motor city in a stunning production packed with hit after hit, all killer, and no filler! Dancing in the Streets is performing at the Fox Theatre for the first time"_

Throwing the error `Uncaught TypeError: Cannot read property 'pos' of undefined`

It works if you remove the exclamation point after _"filler"_ but not if you remove everything after _"filler"_.

Another example (simply adding a comma to this sentence):

Works: _Come experience the energy and electricity of the motor city in a stunning production packed with hit after hit_

Doesn't work: _Come experience the energy and electricity of the motor city in a stunning production packed with hit after hit,_

**Comment by spencermountain** [comment]
agh! thanks! I'll fix this tomorrow morning. I think I know what it is.

**Comment by tsadykhov** [comment]
no problem :) Thanks for the great package!

**Comment by spencermountain** [comment]
hey man, think i fixed it, can you try it now?
http://nlpcompromise.com
cheers

**Comment by tsadykhov** [comment]
just ran it through a bunch of my use cases and it passed on all of them. great work!
