### ISSUE TITLE
Verb tense: nlp.verb("open").conjugate()  -> "oping" as gerund?

### ISSUE THREAD

**Issue by joel-custlabs** [nlp-compromise/nlp_compromise#104]
Steps to reproduce;

nlp.verb("open").conjugate()

Observed results:
{ infinitive: 'ope',
  gerund: 'oping',
  actor: 'oper',
  present: 'opes',
  past: 'oped',
  future: 'will ope',
  perfect: 'have oped',
  pluperfect: 'had oped',
  future_perfect: 'will have oped' }

Expected result: open - opening - etc

**Comment by joel-custlabs** [comment]
This happens, because verb\conjugate\predict_form   matches via suffix_rules the -en suffix as  "participle", instead of infinite. This bug also impacts, off the top of my head: garden, happen, listen, lighten, loosen

**Comment by spencermountain** [comment]
ahh, thanks Joel. Will take a look at this tonight. Nice find, and thanks for the well-researched issue

**Comment by spencermountain** [comment]
hey, open,  garden, happen, listen, lighten, loosen all work properly now. woo! will roll-out in 4.5.1

**Comment by joel-custlabs** [comment]
👍   thank you!
