### ISSUE TITLE
`.root()` returns text of a function

### ISSUE THREAD

**Issue by josephrocca** [nlp-compromise/nlp_compromise#108]
There's something weird going on here:

![image](https://cloud.githubusercontent.com/assets/1167575/14908846/2606c874-0e0f-11e6-9c29-c22afaab43f7.png)

A bug that has been introduced recently?

**Comment by spencermountain** [comment]
ahh!
thanks. will check it out!

**Comment by josephrocca** [comment]
No worries :+1:

**Comment by spencermountain** [comment]
hey, i got this fixed, check it out in `v4.9.1`.
It's an undocumented/sorta-experimental method, my idea being `text.normal()` still needs to be readable, but `text.root()` can be way more aggressive. Let me know if it's doing what you'd like it to.
cheers!

**Comment by josephrocca** [comment]
Still returns function text for me. Tried in 4.9.1 and 4.10.1
Something I'm doing wrong on my side?
Cheers

**Comment by spencermountain** [comment]
hey joseph, i may have just forgotten to build it, should be fixed now
```
console.log(nlp.text('she sells seashells').root());
//she sell seashells
```
cheers

**Comment by josephrocca** [comment]
All good now! :+1: 

Great work with the library - as it becomes more stable I think it'll come in handy on quite a few projects - thanks!
