### ISSUE TITLE
Compatible with ES6/ES2015? -- Cannot find module

### ISSUE THREAD

**Issue by cjke** [nlp-compromise/nlp_compromise#114]
Awesome library. 

I have been using it successfully outside of ES6, usually via the CDN, however I am now trying to bring it into a ES6 project and it seems to choke on the import.

I am using browseify / babelify if that helps. 

The output is:
```
Cannot find module './term/term.js' from '/[project-path]/node_modules/nlp_compromise/builds'
```

This is from a simple import:

```
import nlp_compromise from 'nlp_compromise';
```

**Comment by spencermountain** [comment]
ah, nuts. thanks Chris, will take a look

**Comment by cjke** [comment]
Na man all good. Great library. We are looking at using it an upcoming project, and was knocking together a few spikes (here's a mini mini spike with React http://jsbin.com/govomanaca/edit?output  -- ignore my shocking code)

I will look at the contributing guide too, maybe PR's are better in the future

**Comment by spencermountain** [comment]
oh, think i figured this out today.
browserify supports a "browser" key in package.json
this works like it should now.
cheers
