### ISSUE TITLE
Lots of past tense issues

### ISSUE THREAD

**Issue by PaulBGD** [nlp-compromise/nlp_compromise#118]
Here's a few examples I found
![Image](https://i.imgur.com/yFizkAN.png)

**Comment by spencermountain** [comment]
ah, thanks Paul. I'll take a look.
p.s. your streams library is amazing

**Comment by PaulBGD** [comment]
Thanks man! It was just part of an experiment I was working on where I was making small libraries for smaller browsers, but I'm glad you found it useful.

**Comment by spencermountain** [comment]
whoa, this was a doozy, but it's looking a lot more reasonable now:
```javascript
let s=nlp.sentence('he is currently doing everything he can to stop the problem')
s.to_past().text()
//he was currently doing everything he could to stop the problem
s.to_future().text()
//he will be currently doing everything he can to stop the problem
```
i'll admit, this brought me to some dark places.
thanks!

**Comment by PaulBGD** [comment]
Nice!
