### ISSUE TITLE
Firefox function instead of string

### ISSUE THREAD

**Issue by wybiral** [nlp-compromise/nlp_compromise#119]
#### Error:
> TypeError: str.indexOf is not a function

#### Notes:
The implementation of `endsWith(str, suffix)` is being called with `str` as a function, the origin of the call is from `gerund(o)`.

#### PS:
This doesn't happen when you run the demo in 4.10.5 because that demo is pulling the library from `https://npmcdn.com/nlp_compromise@3.0.6/builds/nlp_compromise.min.js`. If you change that to 4.10.5 the demo fails as above. Simply loading that library in Firefox fails.

**Comment by spencermountain** [comment]
AHHHH!

**Comment by spencermountain** [comment]
Davy, thank you so much for this.
I've rolled-back the used library version to 4.5.1, and the website loads now. That was a great idea.

The issue involves me forgetting to use `hasOwnProperty`, and the word 'watch' gets conjugated, it passes-around Object.watch(). 
I'll look at a proper fix for this very soon
cheers man

**Comment by wybiral** [comment]
:+1: 

PSS: So far this is a really cool Javascript library! I'll definitely be thinking of ways to leverage this kind of functionality in future projects.
