### ISSUE TITLE
RFC: Functional API?

### ISSUE THREAD

**Issue by nateabele** [nlp-compromise/nlp_compromise#120]
Would you accept a patch to convert the API to return immutable objects instead of mutating the base value?

Should make things like...
> caching by sentence, so unchanged-sentences aren't re-parsed on keystroke

...easier to implement.

Would also obviate this:
> some kind of thorough memory-leak test

**Comment by sotojuan** [comment]
Would be interested in helping to implement this if accepted.

**Comment by spencermountain** [comment]
hey guys, I like this idea too. It's a pretty big one. Join the conversation in #89 ? I think it's up your alley.

Right now the methods are sometimes mutable, sometimes not, which is brutal. it would definitely make sense to go one way or the other. Would love some help with this. I'm nearly-instantly confused by it.
