### ISSUE TITLE
Whitelist directories for a smaller module size

### ISSUE THREAD

**Issue by sotojuan** [nlp-compromise/nlp_compromise#121]
Currently if you install the npm version of this library you are downloading everything in this repo, including builds, demos, tests, and docs (`builds/`, `demo/`, `test/`, `doc/`).

There's no need to include this in the npm package—when you `npm install` you expect the "production" version of the library. It's wasteful to download development stuff like tests and docs. If a user is interested in those, they can clone or fork the repo.

Let me know what you think. I'm happy to contribute with a PR if you like this idea. This is a [common](https://github.com/sindresorhus/ava/blob/master/package.json#L44) and recommended technique and can be used with npmcdn.

**Comment by spencermountain** [comment]
ah, definitely Juan. I didn't know this was possible. Love it, sounds good!

**Comment by sotojuan** [comment]
Thanks. Is the `plugin` directory needed or is it just there as an example?
