### ISSUE TITLE
BUG: Project perpetuates gender binarism

### ISSUE THREAD

**Issue by DominoTree** [nlp-compromise/nlp_compromise#122]
Binary gender has been deprecated.  This project should be updated to support a modern fluid gender specification.

**Comment by silentrob** [comment]
This is a duplicate issue, and ongoing discussion happening on GH-117.

**Comment by entd** [comment]
"Binary gender has been deprecated" - [citation needed]

**Comment by RRorg** [comment]
Even if the initial claim of binary gender being deprecated is true, this library would still be useful to parse legacy pieces of English language. Sorry for nitpicking!

**Comment by masterslavedb** [comment]
Only 0.3% of the US population identifies as transgender. 

http://williamsinstitute.law.ucla.edu/research/census-lgbt-demographics-studies/how-many-people-are-lesbian-gay-bisexual-and-transgender/

**Comment by DominoTree** [comment]
@masterslavedb that's great... What about some of the other definitions?

https://s-media-cache-ak0.pinimg.com/736x/3f/b9/df/3fb9df813f5d71f6151dfbaae6cc9a70.jpg
