### ISSUE TITLE
Place can also be airport codes (eg JFK)

### ISSUE THREAD

**Issue by jashsayani** [nlp-compromise/nlp_compromise#127]
The `place` API is interesting, in that the library knowns about places. Not sure if places belongs here but if we have cities, then airport codes can also be very useful.

Example: Find flights from JFK to SFO.

An alternate would be to have "data-plugins" that define sets for categories like places. So an airport plugin can be used that would recognize airport codes as places.

**Comment by spencermountain** [comment]
ah! very neat idea. I like this a lot.
happy to support this one in master.
let me get through some backlogs..
thanks

**Comment by ilyankou** [comment]
Waiting to be merged. The only issue is, since all tokens are returned via filter(), they contain punctuation marks. That is, "Traveling to LAX?".places() will return ["LAX?"].

**Comment by spencermountain** [comment]
yeah, perhaps we need some kind of granular `term.strip_punctuation()`, or something. Very nice ilya
