### ISSUE TITLE
Syllable hyphenation fails for the dipthong 'eu'

### ISSUE THREAD

**Issue by hherman1** [nlp-compromise/nlp_compromise#130]
Using the 'Syllable hyphenation' demo from http://nlp-compromise.github.io/website/#demos produces a syllable for each of 'e' and 'u' for the word 'eulogy', while the correct breakdown would be 'eu' 'log' 'y'.

**Comment by spencermountain** [comment]
ah, that's a good one.
I'll add this one to the stack.
cheers!

**Comment by factormystic** [comment]
I've also logged a few problems over on that repo. Should all problems come here instead? https://github.com/nlp-compromise/nlp-syllables/issues/2
