### ISSUE TITLE
Method to list nouns and verbs in a sentence

### ISSUE THREAD

**Issue by geekodour** [nlp-compromise/nlp_compromise#132]
I have seen the example and the attached sources, but I am not able to find a good solution to get the nouns or verbs from a given sentence. Is this a feature to be implemented? I am thinking of contributing to it.

**Comment by spencermountain** [comment]
hi Hrishikesh, Thanks. yeah, I think there used to be helper-methods for this.
Right now you can do this:
```javascript
nlp_compromise.sentence("The giraffe ate the apples.").terms.filter((t)=>{ t.pos.Noun})
// giraffe, apples
```
I think you're right about it drifting around the docs, maybe it should exist again! go for it!

**Comment by spencermountain** [comment]
:metal: Ilya :metal:
