### ISSUE TITLE
Contractions missing whitespace after expansion

### ISSUE THREAD

**Issue by danielfoord** [nlp-compromise/nlp_compromise#139]
Hi guys,

I couldn't find any similar issues reported so here goes:

On your site, the example for contraction expansion expands 

> 
We've only just begun, to live. White lace and promises. We'll start out walkin' and learn to run.

to

> 
We haveonly just begun, to live. White lace and promises. We willstart out walkin' and learn to run.

There is a missing space after the 2nd part of the expanded contraction.

Cheers

**Comment by dleen** [comment]
Will be fixed by #116

**Comment by spencermountain** [comment]
nice one David! thanks!
