### ISSUE TITLE
A general Question

### ISSUE THREAD

**Issue by elgamersitom** [nlp-compromise/nlp_compromise#141]
Hello, i'm trying to do NLP in spanish language, specifically i'm trying to conjugate spanish verbs, i can see in your project that you have a corpus from Node Box which only work on english. So i don't know if there are any corpus that give me the option of conjugate verbs in spanish.

Hope you can help me, bye.

**Comment by spencermountain** [comment]
Hola!
yes, this is a great question. I was really happy to find that nodebox dataset. I don't know about a similar one for spanish, but would love to find one, and would love to help with similar functionality.
have you poked-around in the european wordnet versions? A lot of [these projects](http://globalwordnet.org/wordnets-in-the-world/) are dead, and heavily-licenced😕 , but i've found if you email these people, you may bounce around a bit, but this should exist!
Please let me know if you find something, I'd very-much love to start a es_compromise if we could find it

**Comment by elgamersitom** [comment]
Hello, as you say all the projects are closed. The thing is that you can
find a lot of pages that can conjugate the verbs but you can't access to
their corpus or they don't have an API or something.

If i found something i will tell you, thanks.

2016-05-17 13:41 GMT-05:00 spencer kelly <notifications@github.com>:

> Hola!
> yes, this is a great question. I was really happy to find that nodebox
> dataset. I don't know about a similar one for spanish, but would love to
> find one, and would love to help with similar functionality.
> have you poked-around in the european wordnet versions? A lot of these
> projects <http://globalwordnet.org/wordnets-in-the-world/> are dead, and
> heavily-licenced😕 , but i've found if you email these people, you may
> bounce around a bit, but this should exist!
> Please let me know if you find something, I'd very-much love to start a
> es_compromise if we could find it
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nlp-compromise/nlp_compromise/issues/141#issuecomment-219813757>
>



-- 
Cristian Narváez.
Ingeniero en Multimedia.
Miembro grupo de investigación ACCEDER <http://www.accederresearch.org/>.
Universidad Militar Nueva Granada.
Bogotá-Colombia

**Comment by spencermountain** [comment]
just closing this, for housekeeping, but very interested in this

**Comment by elgamersitom** [comment]
Hello i found something,

you can use pattern lib for python [http://www.clips.ua.ac.be/pages/pattern-es](Here's the Spanish version), with this lib you can get Spanish verbs and their conjugations as it is a NLP library. Also i try different functions from the pattern.en and they also work on pattern.es, so i think they support multiple languages.
I don`t really know how to structure the new messages, by now i'm playing with automatic conjugation.

I hope this info is useful for you, bye.
