### ISSUE TITLE
Wrong conjugation for `speak`, `criticize`, `develop`

### ISSUE THREAD

**Issue by ndarville** [nlp-compromise/nlp_compromise#143]
## Speak ##

- [x] **Perfect:** have spoke
- [x] **Pluperfect:** had spoke
- [x] **Future perfect:** will have spoke

## Criticise ##

- [x] **Participle:** criticisen
- [x] **Perfect:** have criticisen

## Develop ##

- [x] **Gerund:** developping

**Comment by spencermountain** [comment]
thanks Niclas, 

- [ ] **been** #131 
- [ ] **doing, can, stop** #118
