### ISSUE TITLE
Error: Cannot find module 'nlp-ngram'

### ISSUE THREAD

**Issue by LAMike310** [nlp-compromise/nlp_compromise#151]
Hello, 

I'm trying to use the "nlp-ngram" plugin from the ReadMe, but I get the error when trying to run the example:
"Error: Cannot find module 'nlp-ngram'"

I've done a npm install of the "nlp-gram" module, and I have required nlp itself in the script too. Is there a step I'm missing in order to get the plugin to work?

Here's the script currently:

```
var nlp = require("nlp_compromise")
nlp.plugin(require("nlp-ngram"));
var t4 = nlp.text(`Tony Hawk played Tony Hawk's pro skater`);
t4.ngram({min_count: 2});
```

Thanks for any help!

**Comment by TheOtherDude** [comment]
Not sure why this happening, but you can require the file directly to get it working:

var nlpNgram = require('./node_modules/nlp-ngram/builds/nlp-ngram')

**Comment by mraypold** [comment]
I was able to fix this by changing the "main" property in package.json in the nlp-gram library.

Change `"main": "builds/nlp-ngram.es5.js"` to `"main": "builds/nlp-ngram.js",`

**Comment by spencermountain** [comment]
nice one Michael 💪 
thanks guys
