### ISSUE TITLE
Add new city to places

### ISSUE THREAD

**Issue by rheza** [nlp-compromise/nlp_compromise#154]
Hi,  I already try added the city on the places.js file, but it's still failing. Is there any documentation to add new city name on places? 

Thanks

**Comment by spencermountain** [comment]
hi Rheza! it sounds like you need to run a `grunt build`, in order for the ./src files to compile. That should do the trick.

it's probably easier though, to [augment the lexicon via the api](https://github.com/nlp-compromise/nlp_compromise/blob/master/docs/api.md#augmenting-the-lexicon)
is that helpful?
cheers

**Comment by rheza** [comment]
That was really helpful. Thank you. 

Can i have an example for places() on augment the lexicon?,

**Comment by rheza** [comment]
Nahhh,  I think I got it. 

Thanks

**Comment by arpa1banerjee** [comment]
How do I add new Cities? Can you please explain. I am using the latest compromise module 9.0.0

**Comment by spencermountain** [comment]
sorry the docs moved, for reference in v9:
https://runkit.com/583f2a3dc534df0014136221/58e3fa50eb531700140a908c

**Comment by arpa1banerjee** [comment]
Thanks a lot Spencer
