### ISSUE TITLE
Feature Request: Get what the amount is of

### ISSUE THREAD

**Issue by 2426021684** [nlp-compromise/nlp_compromise#158]
Add `ofWhat` property.

`nlp_compromise.value("5 boxes").ofWhat` would equal boxes.
`nlp_compromise.value("5.3 kg of copper").ofWhat` would equal copper.

There probably is a better name than `ofWhat`.

**Comment by spencermountain** [comment]
YES! love this.
right now this works:
`console.log(nlp.value('5 boxes').unit);`
but this could be much better, as your second example shows.

**Comment by 2426021684** [comment]
`nlp.value("1 cup water").of_what = "cup"` Should it be `"water"` or `"cup"`? I think it should be `"water"`.

**Comment by spencermountain** [comment]
looks like this example works now. :dancer:

**Comment by 2426021684** [comment]
@spencermountain
```
> nlp.value("1 cup water").of_what
'cup'
```
should be water
