### ISSUE TITLE
Incorrect tagging

### ISSUE THREAD

**Issue by rupeshk** [nlp-compromise/nlp_compromise#159]
Please see this case: Transfer $500 to John for going to New York. Here Transfer is tagged as noun. I tried adding transfer as verb to lexicon (lexicon["Transfer"] = "Verb") but it doesn't seem to work.

Also how can value such as $500 be interpreted as currency.

**Comment by spencermountain** [comment]
ah, two good ones Rupesh!

**Comment by spencermountain** [comment]
got it :muscle: 
thanks dude
