### ISSUE TITLE
"Feauture" request: TypeScript definition file

### ISSUE THREAD

**Issue by eshansingh** [nlp-compromise/nlp_compromise#162]
A lot of us now-a-days are using Angular 2 with TypeScript, and we would love to see a definition file (`.d.ts`) for `nlp_compromise`. I'm willing to volunteer in the making of it, but I wouldn't want to do it alone as `nlp_compromise` is a pretty large library.

Thoughts? More volunteers?

Thanks!

**Comment by 2426021684** [comment]
If you want me to take a stab at it, I might be able to.

**Comment by eshansingh** [comment]
@2426021684 Thanks! Where I'm living it's night right now, so I'll create a temporary repo for it tomorrow. I'll wait for maybe 2 more volunteers if possible.

**Comment by 2426021684** [comment]
I looked at the api. I don't think it will take four people. I am going to start. If what I make is good I will post it.

**Comment by eshansingh** [comment]
@2426021684 OK, thanks a lot!

**Comment by 2426021684** [comment]
Is the api stable?

**Comment by eshansingh** [comment]
Pretty sure, yes.

On Fri, May 27, 2016, 12:19 AM 2426021684 <notifications@github.com> wrote:

> Is the api stable?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nlp-compromise/nlp_compromise/issues/162#issuecomment-221960218>
>
-- 

<https://mail.google.com/mail/u/0/>

[image: Github]  <https://htmlsig.com/t/000001BH5P8Z> [image: Stack
Overflow]  <https://htmlsig.com/t/000001BPHR5R>

Eshan Singh
eshansingh@gmail.com / +917719939040

I make stuff.

**Comment by 2426021684** [comment]
I got some done. https://github.com/2426021684/nlp-compromise-typings/

**Comment by 2426021684** [comment]
I got more done. The docs are not that helpful. There are tons of undocumented methods. I left notes in the file.

**Comment by 2426021684** [comment]
I added you as a collaborator.

**Comment by eshansingh** [comment]
Thanks! Sorry for replying so late. I cloned the repo, am working on it!

**Comment by 2426021684** [comment]
I am going to sleep now. I will start from were you left off tomorrow.

**Comment by spencermountain** [comment]
hey guys! sorry I just saw this. I'd love to help. I like typescript, and am happy to maintain this once the api changes. There are a lot of undocumented methods!
Wanna put it in this repo? do most people have a .d.ts file in `./` ? Let's do that?
PR!

**Comment by eshansingh** [comment]
We have a repo at https://github.com/2426021684/nlp-compromise-typings/, and after we're done we'll submit a PR to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo. And undocumented? _Understatement_! @2426021684 and I have been trying this for a while now, and the documentation is utterly inadequate. That's a separate issue, though it deserves attention later, because this is a really awesome library, but it needs better documentation, not just in wikis and such, but also self-documenting within the code with comments and better variable names.

**Comment by 2426021684** [comment]
@spencermountain The documentation needs some serious work. I gave up reading it. I am just using a repl and looking at the code. What is `pos` ? How should I type it?

**Comment by spencermountain** [comment]
thanks Eshan. I completely agree. I didn't anticipate the attention this library would get. 
In terms of self-documentation, are there any tools or practices you'd recommend? I've thought about adding flow annotations, or jsdoc comments, but haven't been following what's best-practice these days in javascript-land.
I suppose you two have done the hard work already. would flow or jsdoc be redundant? Can these things be converted/shared?
thanks

**Comment by spencermountain** [comment]
hi @2426021684  thanks for all of your hard work. `term.pos` is an object containing the parts of speech as strings, the possible keys are found in  [https://github.com/nlp-compromise/nlp_compromise/blob/master/src/sentence/pos/parts_of_speech.js#L95](parts_of_speech.js). Does that help?

**Comment by eshansingh** [comment]
@spencermountain I'm not a professional developer by any extent, but I will say that the most important thing is to get your names right. JSDoc is good, but it's not the first thing you should do. The code, without any comments, JSDoc or otherwise, should be understandable to an extent.

**Comment by eshansingh** [comment]
@spencermountain: @2426021684 and I are (probably) on opposite sides of the world. It's night right now here, and it's morning on @2426021684's end. It might be a bit difficult to co-ordinate us. However I am doing an all-nighter for some work for a separate project, so I can do some stuff in bewteen.

**Comment by 2426021684** [comment]
@spencermountain You could switch the entire repo to typescript. That would make it more readable. @eshansingh and I can just add our annotations to it. When you compile typescript you can have it emit a d.ts.

**Comment by eshansingh** [comment]
@spencermountain In addition, check out [this](http://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670?ie=UTF8&keywords=Code Complete&qid=1464367572&ref_=sr_1_1&sr=8-1) book. It doesn't talk about JS specifically, but it does have a _lot_ of awesome advice. I recommend it.

**Comment by 2426021684** [comment]
@eshansingh Can you commit what you have?

**Comment by eshansingh** [comment]
@2426021684 Possible but an even bigger ordeal than what we're doing now. It's better to make documentation better.

**Comment by eshansingh** [comment]
@2426021684 It's not much at all (seriously!), but I will. Give me a second.

**Comment by 2426021684** [comment]
https://www.npmjs.com/package/tsdoc could be an option

**Comment by eshansingh** [comment]
@2426021684 Done.

**Comment by eshansingh** [comment]
@2426021684 I left some comments on your // Improve comments.

**Comment by 2426021684** [comment]
@eshansingh great. I think it would be better if the typings were here instead of on DT.
https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by eshansingh** [comment]
@2426021684 Most commonly people look for their definitions using `tsd` or `typings`. Maybe we could publish on both? But then updating would be difficult.

**Comment by eshansingh** [comment]
Linking: https://github.com/2426021684/nlp-compromise-typings/issues/1

**Comment by 2426021684** [comment]
@eshansingh tsd is deprecated

**Comment by 2426021684** [comment]
@spencermountain a couple of methods have an `options` arg. What are the options?

**Comment by eshansingh** [comment]
@2426021684 [`typings`](https://github.com/typings/typings) is the official replacement, and it can search DT.

**Comment by eshansingh** [comment]
@2426021684 And yes, exactly. The `options` arg is a bit vague on what exactly we can pass. If we knew this we could make an interface for it, to offer better type checking.

**Comment by eshansingh** [comment]
@spencermountain?

**Comment by eshansingh** [comment]
Shit clicked the close button

**Comment by 2426021684** [comment]
`typings` can also install from npm. https://www.npmjs.com/package/typings

**Comment by eshansingh** [comment]
@2426021684 Oh yes good point.

**Comment by spencermountain** [comment]
ah, i love that there's more support for this stuff now. I'd love to keep an up-to-date copy of this locally, and link it in package.json. If you add it to `definetlyTyped` or elsewhere, let me know and i can remember to update it there too. This is a huge, huge help.

One question to you both, once we have these typings, is there a systematic way to test with them, short of a large typescript re-write? Can I hook the typings file into the test runner somehow? 

...or said another way, how can we know when there's an issue with the typings file? It'd be great to have a systematic way to keep an eye on it, as the library changes. Happy to try anything.
thanks,

**Comment by 2426021684** [comment]
@spencermountain  I think we are putting the d.ts file here. You could write the tests in typescript. There many be other ways to test a d.ts file. I think documentation can be generated from them too.

**Comment by 2426021684** [comment]
@spencermountain is `pos` going to be accessed like `pos["key"]` or `pos.key`? Typescript can only type check pos.key.

**Comment by eshansingh** [comment]
@spencermountain I'm not entirely sure how to do that, but that is really important. It's getting pretty late for me right now, so I'm wrapping up. I'll look into it later.

**Comment by 2426021684** [comment]
I think the only way to test it is to write the tests in typescript.

**Comment by 2426021684** [comment]
@spencermountain Can you check what we have so far? Just edit anything that is wrong.

**Comment by eshansingh** [comment]
@2426021684 OK, I'm back. Will do a pull of the rep.

**Comment by 2426021684** [comment]
Going to sleep now. Will be back tomorrow.

**Comment by eshansingh** [comment]
JavaScript (and therefore TypeScript) allow
the usage of an array syntax and it means exactly the
same thing. It's true that TS can only type check x.pos.key
however if someone uses the former method then nothing really
happens. Regardless of whether @spencermountain used one or the other, the property can be accessed both ways.

**Comment by 2426021684** [comment]
Ok, that makes sense

**Comment by eshansingh** [comment]
Would like to link references: [DT Contribution guidelines](http://definitelytyped.org/guides/contributing.html) and [DT Best Practices](http://definitelytyped.org/guides/best-practices.html). Though we're not planning to submit to DT, it's a good idea to have a look at these.

**Comment by eshansingh** [comment]
@spencermountain What is `tokenize_match` and what is it supposed to return?

**Comment by eshansingh** [comment]
@spencermountain @2426021684 I have added testing with `gulp`. See my comments.

**Comment by eshansingh** [comment]
See https://github.com/2426021684/nlp-compromise-typings/issues/2. Separate thread to ask questions to @spencermountain

**Comment by eshansingh** [comment]
@spencermountain So `tokenize_match` wasn't meant to be a public facing method. OK, thanks!
