### ISSUE TITLE
Make a wiki

### ISSUE THREAD

**Issue by eshansingh** [nlp-compromise/nlp_compromise#166]
As @2426021684 and I pointed out in #162, the documentation for `nlp_compromise` leaves much to be desired. I believe the first step we can take to do this is to make a wiki for `nlp_compromise`.

**Comment by spencermountain** [comment]
yeah, you're probably right about this. Not sure why not ;)
[go nuts!](https://github.com/nlp-compromise/nlp_compromise/wiki)
