### ISSUE TITLE
Unit now includes of_what

### ISSUE THREAD

**Issue by 2426021684** [nlp-compromise/nlp_compromise#173]
In previous versions, `nlp_compromise.value("12 g sugar").unit = "g"`. Now it is equal to `"g sugar"` and is no longer recognized as a weight.

**Comment by spencermountain** [comment]
hey @ilyankou wanna check it out?

**Comment by spencermountain** [comment]
hey nevermind, I'm gonna kick up some dust this evenin'

**Comment by ilyankou** [comment]
I can have a look at it in a few hours, @spencermountain
