### ISSUE TITLE
"4 cats" and "4 red cats" are parsed very different

### ISSUE THREAD

**Issue by 2426021684** [nlp-compromise/nlp_compromise#194]
"4 cats" => Value("4 cats")
"4 red cats" => Value("4"), Adjective("red"), Noun("cats")

Why are they parsed so differently?

**Comment by spencermountain** [comment]
yeah, this is a tough case.
i think in the future, we'll want `"4 cats" => Value(4), Noun('cats')`
then our value parsing method jumps around the sentence, interpreting `.of_what()` etc.

**Comment by 2426021684** [comment]
I agree

**Comment by 2426021684** [comment]
Or maybe have hierarchical terms. Have value contain `Value(Number(4), Noun(Adjective("red"), Noun("cats")))`

**Comment by ilyankou** [comment]
Resolved, waiting to be merged. (#204)
