### ISSUE TITLE
Question about of_what

### ISSUE THREAD

**Issue by 2426021684** [nlp-compromise/nlp_compromise#200]
What should `nlp.value("5 boxes of water").of_what` return? It currently returns `"water"`. I was expecting `"boxes of water"` since boxes is not a unit.

**Comment by ilyankou** [comment]
Your point makes sense, `of_what` is pretty raw (and simple) right now, and there are lots of phrases for which we should determine the method's behavior (e.g. "full of these things", "5 boxes of bottles of water" etc).

**Comment by 2426021684** [comment]
In my opinion:
"full of these things" (is this even a value?) => "these things" 
"5 boxes of bottles of water" => "boxes of bottles of water"
