### ISSUE TITLE
How can I get the tense of a determinate verb

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#203]
Hi,

I have the term `won't` but when I execute the method `conjugation` always returns `infinitive`. Is this the normal behavior? I wonder it should be `future` (or something like that). If it's the normal behavior how can I get the tense?

thanks in advance 👍

**Comment by spencermountain** [comment]
ah yeah, you're looking for something that returns either past, present, or future? yeah, that sounds reasonable. Ideally things like 'grammatical number' should have their own specific method too.
i'll add this to the list. For what it's worth, it may just be as simple as this mapping:
```javascript
{ infinitive: present,
  gerund: present,
  present: present,
  past: past,
  actor: null,
  future: future,
  perfect: past,
  pluperfect: past,
  future_perfect: future }
```

**Comment by spencermountain** [comment]
gerunds like "walking" are a little ambiguous - "was walking - vs - is walking"

same for perfect tense, "have cared", which is like both `past & present` ...?

but a past/present/future split seems like a fair idea. what's your use-case?
