### ISSUE TITLE
`3 buses` and `3 trains`

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#205]
Unfortunately the terms are different for the first is `value = 3 buses` and for the second one `value = 3` and `verb = trains`. Maybe you have to improve the rules :)

by the way, thanks for this library it is so helpful for my new project,

best

**Comment by ilyankou** [comment]
Resolved, waiting to be merged (#204)

**Comment by spencermountain** [comment]
💥
