### ISSUE TITLE
Guessing part of speech?

### ISSUE THREAD

**Issue by zeke** [nlp-compromise/nlp_compromise#208]
I know context is required to accurately determine a word's part of speech, but does this library provide a way to guess (or pick the word's most common part of speech)?

Something like...

```js
nlp.term('cheese').pos()
// => probably a noun
```

**Comment by ilyankou** [comment]
This library is basically "guessing" each word's part of speech based on it's spelling, and then makes minor adjustments depending on the context.

So,

    nlp.sentence('cheese')

is an object that contains the following:

```
Sentence {
  str: 'cheese',
  terms: 
   [ Noun {
       whitespace: [Object],
       text: 'cheese',
       normal: 'cheese',
       expansion: null,
       reason: 'lexicon_pass',
       pos: [Object],
       tag: 'Noun' } ],
  contractions: { expand: [Function], contract: [Function] } }
```

As you see, `tag: 'Noun'`.

**Comment by spencermountain** [comment]
exactly. The perfect tagger also should know the user's cultural setting too, like 'smashed' means drunk in america, but tired in britain...
so often the sentence/text is not even enough.

This library just tries to 80-20 rule the most-common pos, in an opinionated-but-fair way. If you know the context in advance, you can coerce certain words [like this](https://github.com/nlp-compromise/nlp_compromise/wiki/Lexicon).
but like Ilya says, 
```javascript
nlp.sentence("the cheese").tags()
// Noun
nlp.sentence("he would cheese the bagel").tags()
// Verb
```
cheers

**Comment by zeke** [comment]
Good stuff. Thanks @ilyankou and @spencermountain
