### ISSUE TITLE
Some nouns are mistaken for adjectives

### ISSUE THREAD

**Issue by motet-a** [nlp-compromise/nlp_compromise#210]
In the sentence _"The current directory."_, the noun _directory_ is mistaken for an adjective, and is "grouped" with _current_:

```js
> nlp.sentence('The current directory.')
Sentence {
  str: 'The current directory.',
  terms: 
   [ Term {
       whitespace: [Object],
       text: 'The',
       normal: 'the',
       expansion: null,
       reason: 'lexicon_pass',
       pos: [Object],
       tag: 'Determiner' },
     Adjective {
       whitespace: [Object],
       text: 'current directory.',
       normal: 'current directory',
       expansion: null,
       reason: 'rules_pass_18',
       pos: [Object],
       tag: 'Adjective' } ],
  contractions: { expand: [Function: expand], contract: [Function: contract] } }
```

But if I replace _directory_ by a more common noun like _car_ or _monkey_, everything works as expected.

There is the same issue with _repository_ used as a noun too.

Thanks for this great library :-)

**Comment by motet-a** [comment]
I just realized I can solve this issue by adding the word _directory_ to the lexicon as a noun. But wouldn't it cause other issues if I use _directory_ as an adjective in a sentence such as _"The directory assistance."_ ?

**Comment by ilyankou** [comment]
The pos parser marks "directory", "repository" due to rules_pass_20:
```javascript 
 ['.[oe]ry$', 'JJ']
```
That is, the parser marks anything that ends with -ory/-ery as an adjective. Now, have a look at the list: https://en.wiktionary.org/wiki/Category:English_words_suffixed_with_-ery
It is pretty clear such words are nouns. @spencermountain shall the rule be changed to mark these as nouns?
```javascript
 ['.[oe]ry$', 'NN']
```
All current tests pass, I just checked.

**Comment by spencermountain** [comment]
wow. sure. That's pretty good argument ;) 
thanks.
`Adjective Adjective` should probably not combine either. That seems like sloppy behaviour also, to me.
go nuts!

**Comment by spencermountain** [comment]
also, if **Category:English_words_by_suffix** is generated by-hand, I think I will cry

**Comment by ilyankou** [comment]
Fixed, waiting to be merged.
