### ISSUE TITLE
Some verbs are detected like adjetives

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#216]
sometimes an image says more than 1k words :)

<img width="272" alt="screenshot" src="https://cloud.githubusercontent.com/assets/559654/16114968/611f3694-33ee-11e6-9b22-9c809e1f79bc.png">

**Comment by spencermountain** [comment]
😱 🙀 😱 
thanks, that's funny. will take a look.

**Comment by ilyankou** [comment]
It is tricky here.
```javascript
Sentence {
  str: 'it is raining now',
  terms: 
   [ Noun {
       whitespace: [Object],
       text: 'it',
       normal: 'it',
       expansion: null,
       reason: 'lexicon_pass',
       pos: [Object],
       tag: 'Pronoun' },
     Verb {
       whitespace: [Object],
       text: 'is',
       normal: 'is',
       expansion: null,
       reason: 'lexicon_pass',
       pos: [Object],
       tag: 'Copula' },
     Adjective {
       whitespace: [Object],
       text: 'raining',
       normal: 'raining',
       expansion: null,
       reason: 'rules_pass_62',
       pos: [Object],
       tag: 'Adjective' },
     _Date {
       whitespace: [Object],
       text: 'now',
       normal: 'now',
       expansion: null,
       reason: 'lexicon_pass',
       pos: [Object],
       tag: 'Date',
       data: [Object] } ],
  contractions: { expand: [Function], contract: [Function] } }
```

`rules_pass_62` is this RegExp:
```javascript
`/.[pdltrkvynsw]ing$/i`
```

**Comment by spencermountain** [comment]
this is brilliant Ilya. Yep, sounds right to me.
maybe [Copula] + [Gerund] => [PresentTense] - just in case?

`rules_pass_62` looks like a crap rule, too. Do what you want 🍻  !

**Comment by ilyankou** [comment]
So the way I am trying to approach this is:
if Coupla + Verb exists in verb's conjugates, then it should be one single verb ("am doing", "will call").
This way passive voice will remain two separate words ("the letter [was] [sent]").

**Comment by spencermountain** [comment]
sounds good to me.
just watch out for "is nice", or mis-identified adjectives
