### ISSUE TITLE
Concept of sentence

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#221]
Hi,

Before I used another library, *Salient*, which has a method called `concepts` which gives you a array of concepts of your sentence. This kind of methods are very useful in combination with a classifier, for example IBM Alchemy has one too.

My purpose is include this method in NLPCompromise, here is how Salient do it: https://github.com/nyxtom/salient/blob/master/lib/salient/glossary/glossary.js

**Comment by spencermountain** [comment]
ooh! Salient is cool!
thanks!

**Comment by soyjavi** [comment]
Yeah man, Salient has great methods but I remove from my project 'cause has a lot of npm-dependencies... How about replicate the method `concepts` I remember Compromise have something like `topics` right?

best,

**Comment by spencermountain** [comment]
yeah, is this what you are talking about? [.topics()](https://github.com/nlp-compromise/nlp_compromise/wiki/API#named-entity-recognition)
do you wanna join the slack group?

**Comment by spencermountain** [comment]
hey Javi, I'm pleased with .topics() right now. am cleaning-out issues today.
cheers

**Comment by soyjavi** [comment]
+1 in which release will be available?

**Comment by spencermountain** [comment]
Text.topics() is already available. sorry if the documentation is old.
it's not very clever. it's really just `Text.people() + Text.places()...`, and needs a lot of work
