### ISSUE TITLE
adverb.conjugate() is not implemented

### ISSUE THREAD

**Issue by brandonJY** [nlp-compromise/nlp_compromise#222]
I saw nlp.adverb.conjugate which is mentioned in API doc https://github.com/nlp-compromise/nlp_compromise/wiki/API#adverb-methods
has not been implemented. 

Currently only nlp.adverb.to_adjective has been implemented. Is there a plan to wrap it with conjugate function in the future? Or should we just update the API docs?

**Comment by spencermountain** [comment]
hey brandon, yeah totally. what functionality would you expect? The docs kinda suck. I was thinking each class could have a `.all_forms()` method. Would that do the trick?
thanks, will update the docs

**Comment by brandonJY** [comment]
Yeah. I think ``.all_forms()`` would be beneficial in a long run.
