### ISSUE TITLE
Did the API change?

### ISSUE THREAD

**Issue by franciscop** [nlp-compromise/nlp_compromise#226]
I used this library over a year ago, however I'm seeing some oddities:

- I have installed the version 1.1.2 as in the `package.json` like `"nlp_compromise": "^1.1.2"` while the top version on Github is the 1.1.0. Also the package inside `node_modules` shows the 1.1.2 version.
- I am using mainly a method, `.tokenize()`, for which I cannot find any information. It seems that now you use `nlp.text('...').sentences` for the same thing as I used tokenize.
- The history of some articles in the wiki doesn't reveal anything from this `.tokenize()`

So, what is going on? Did this change somehow? Was I using an internal feature? How does it come I got a "bigger" version installed? I [am pretty sure it's the same repo though](https://github.com/nlp-compromise/nlp_compromise/issues/47)

**Comment by silentrob** [comment]
Hey @franciscop, the API has changed in the latest version. I would go so far to say that the project has been completely re-written, but I think at it's core it is the same project and solves the same goals. @spencermountain is that fair?

**Comment by franciscop** [comment]
Note: seeing [this issue](https://github.com/nlp-compromise/nlp_compromise/issues/225), it seems you are currently on the 6.2.1. Which [the changelog confirms](https://github.com/nlp-compromise/nlp_compromise/blob/master/changelog.md). However, most people I know check the number from the Github versions, and as you have some numbers there it'll probably lead to a lot of confussion.

I guess then the `.tokenize()` method was removed at some point (which I cannot see in the changelog).

**Comment by franciscop** [comment]
@silentrob fair enough. So my main concerns now are:

- shouldn't github releases be updated to show that?
- shouldn't a breaking change (renaming a feature) in the API be added to the changelog?

**Comment by spencermountain** [comment]
hey Francisco!  ah, yeah - I've stopped doing github tags, That must be the confusion. let me do that now.
Yep, tokenize() is like, implicit now. You can use `nlp.text('..').sentences[0].terms[3]` or whatever

**Comment by spencermountain** [comment]
p.s. your work is really fun and clever.
What's your nlp_compromise project?

**Comment by franciscop** [comment]
@spencermountain fair enough, glad to hear that I didn't go crazy or confused the library (:

Thanks! I used it for my Final Year Project at my University for getting sentences and words and then feeding them into a Neural Network for extracting learning material. Didn't get results as good as expected though.

Did you know with a couple of changes nlp_compromise can parse the **HTML** from Wikipedia articles quite well? (:

**Comment by spencermountain** [comment]
haha, neat!
[there ya go](https://github.com/nlp-compromise/nlp_compromise/releases)
cheers

**Comment by franciscop** [comment]
Awesome. It totally reminds to [when I missed doing NPM releases](https://github.com/picnicss/picnic/issues/99) as I thought they were automatic :laughing:

**Comment by factormystic** [comment]
You're tagging releases in github again now though, right? I subscribe to the releases page rss feed to know when there's a new version.
