### ISSUE TITLE
conjugate 'rain'

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#229]
Hi,

A simple example if you use the sentence `is raining` and try to conjugate to infinitive with `...conjugate().infinitive` the results is `is raine`.

weird right??

**Comment by soyjavi** [comment]
Any advance with this?

**Comment by spencermountain** [comment]
hey, this looks fixed now, in v6.4.4.
💪

**Comment by soyjavi** [comment]
:muscle:

**Comment by soyjavi** [comment]
Thanks man, version `6.4.7` it's super-stable :)
