### ISSUE TITLE
More rats in syntax matching...

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#238]
Hi,

I'm playing with syntax matching (now is part of my library https://github.com/ava-ia/core/blob/0.1.0/src/helpers/syntax.js) and I've found a new *rat*:

**rule**
`convert [value] [currency] [preposition] [currency]`

**test: 1**
`Ava, can you convert 20 dollars into euros`
👌

**test: 2**
`Ava I need convert 20 dollars into euros`
👻 (is not detected)

any idea??

**Comment by spencermountain** [comment]
yeah, a couple things going on in that second sentence. That's a pretty-good example.
```
console.log(nlp.sentence('Ava I need convert 20 dollars into euros').terms);
```
i'm glad you're using .match(). It's a bleeding-edge feature and rather twisted-up, but I'm also using it for a couple projects, so am personally commited to re-writing/stabilising it over this summer and the fall.

First, we need to reorganize the tests from mocha to `tape`, then I hope to get to it after. I also want to build a new website. Other bugs always come up too.

have you seen [this](http://superscriptjs.com/)?

cheers

**Comment by soyjavi** [comment]
Another rat... for the sentence `how much is 10 minus 4` and the syntax rule `'[Value] (plus|minus) [Value]'`... nothing :(

**Comment by spencermountain** [comment]
yeah, personally i don't feel that `Value plus Value` should lump together into one term.
I can make this more consistent if you are performing arithmetic between terms.

**Comment by soyjavi** [comment]
It will be helpful if you do it 👍

**Comment by spencermountain** [comment]
both `Value plus Value`  and `"euros"` work now in 6.4.3 💥
