### ISSUE TITLE
'madrid', 'next week' lumping

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#239]
Hi,

which are the changes in this version ?? Do you have some kind of changeset? 'cause I've upgraded from 6.3.1 to 6.4.1 and 10% of my tests doesnt work (topics and syntax ... change a lot).  For example using `topics` 

`I wanna visit London and Madrid next week`

**6.3.1**
[`london`, `madrid`]

**6.4.1**
[`madrid next week`]

Something creepy is going with this release :)

best,

javi

**Comment by spencermountain** [comment]
yep, thanks javi, you're right this is a big one.
can you print-out your failing tests for me? or something like that?

**Comment by soyjavi** [comment]
I test your library in this file https://github.com/ava-ia/core/blob/master/test/processor/compromise.spec.js

**Comment by spencermountain** [comment]
hey there, `madrid next week` is fixed. sorry for the instability

**Comment by spencermountain** [comment]
(heads up though, for the contraction 'wanna')
