### ISSUE TITLE
support Symbol Part-of-Speech

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/nlp_compromise#240]
Pretty funny, I'm trying to create a bot who teach you about *maths* and when I try to use `terms` or `tags` methods for `10 + 4` sentence:

`tags()` returns:
```js
['value', '?', 'value']
```

My first idea was *ok, maybe I can use syntax matching like * `[Value] [?] [Value}` but obviously doesn't work. How about detect the term `operator` instead of `?`

best,

javi

**Comment by spencermountain** [comment]
hah, interesting. Yeah, I don't have any objections to a `Symbol` or `Operator` part of speech. I see how that would be useful in many purposes.

**Comment by spencermountain** [comment]
i suppose symbols, like `&`,  `+` and `/` have all the ambiguities that words do. It'd be helpful, when you see a `*`, to know if it means multiply, or whatever.

**Comment by spencermountain** [comment]
hey, Symbol pos is added in v6.4.2. You're gonna need to handle no spaces, like `8+9=17` yourself.
There are some tough issues with `8 -9` vs `8 - 9`, etc. I don't wanna wade too far into this, but the lumping of terms should be better for you now, cheers
