### ISSUE TITLE
Unnamed place identification

### ISSUE THREAD

**Issue by kittykatattack** [nlp-compromise/nlp_compromise#270]
Hi Everyone,

Words like `beach`, `forest` and `castle` are all places.
Would it be possible for nlp_compromise to tag them as such?

**Comment by spencermountain** [comment]
yeah [you can](https://github.com/nlp-compromise/nlp_compromise/wiki/Lexicon#adding-words) in your own project. I'm a little wary of mixing these concepts with explicit places like 'washington dc.',. .. `a castle` vs `the castle` vs `no castle` etc...

what are you using them for?

**Comment by kittykatattack** [comment]
I'm using them for an adventure game with a generative storytelling component. I'm looking for a way to differentiate different types of objects, particularly places that can be visited.

Also, I'm trying to figure out how best to differentiate between concrete and abstract nouns - that's proving to be difficult. I may have to create my own custom list of nouns and tag them explicitly.

**Comment by spencermountain** [comment]
yep, cool. 
happy to accommodate this better in the lib. Let me know how that goes.
...
in the v7 version, it may be easier to do things like `mystory.match("~go~ to #NounPhrase")` to match all the variants like 'went to the pretty beach', and so on. It's not fully together yet.

love the idea of generative writing, cheers
