### ISSUE TITLE
Throwing error "undefined is not a function (evaluating 'y.startsWith("-")')"

### ISSUE THREAD

**Issue by wezham** [nlp-compromise/nlp_compromise#276]
Every so often rollbar throws up the error -  undefined is not a function (evaluating 'y.startsWith("-")'). 

It comes from the to_number(str) function (li: 6583) 
I am unable to reproduce the error locally and seeking some guidance.

**Comment by spencermountain** [comment]
agh! thanks Wesley. I'll take a look, pronto

**Comment by spencermountain** [comment]
hey Wesley, this is fixed in v6.5.1.
cheers!

**Comment by wezham** [comment]
Thanks :D @spencermountain

**Comment by wezham** [comment]
@spencermountain we are using Bower to install NLP. Can you please push up the changes 🙏

**Comment by spencermountain** [comment]
agh, you know, I thought of this last night- like in the middle of the night.

[here it is](https://github.com/nlp-compromise/nlp_compromise/releases/tag/6.5.1)
chers

**Comment by wezham** [comment]
Thats all good, thanks for that @spencermountain  :)
