### ISSUE TITLE
What verb form is "had flown"?

### ISSUE THREAD

**Issue by kittykatattack** [nlp-compromise/nlp_compromise#277]
Hi,

I'm trying to generate "had flown" from fly.

Using `nlp.verb("fly").all_forms().pluperfect` produces `had flew`

Is there another form I should be using?

Thanks!
kk.

**Comment by spencermountain** [comment]
hey, yeah i think the reason this isn't working is that I don't really know, myself ;)

my guess is that 'had flew' is just a bug. 

ha- [yup](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/term/verb/conjugate/generic.js#L48).

if you want to support that specific one, you can add it to [the irregulars list](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/data/irregular_verbs.js) and it should work. You can see a few pluperfects are already there.
cheers

**Comment by kittykatattack** [comment]
Oh Ok, great to know - thanks!
