### ISSUE TITLE
Distinct Values

### ISSUE THREAD

**Issue by jonaslund** [nlp-compromise/nlp_compromise#278]
Hi

Is there a clever way to only return distinct values.

Say for example this
```
var people = nlp.text("tony hawk dances with tony hawk, and then does a 1080 like Tony Hawk).people();
```
Will return an array with 3 matches of Tony Hawk, and it would be super to be able to only get one match?

**Comment by spencermountain** [comment]
hi Jonas, yeah this is a great point.
there's no dedicated method for this (there should be!), but it can be done somewhat doggedly afterwards, comparing `Term.normal`:

```javascript
var nlp=require("nlp_compromise")
var _=require('lodash')
var people=nlp.text('Tony Hawk is cool. Tony Hawk did a 1080').people()
_.uniq(people.map((term)=>term.normal))
```
...the bigger problem is co-reference resolution, like:
`Tony Hawk is cool. He did a 1080. Mr Hawk is nice. `
cheers!

**Comment by spencermountain** [comment]
(we should totally do co-reference resolution too)

**Comment by jonaslund** [comment]
A faster way to get distinct values for .people() is to filter the array like so. Built in function would be cool but not urgent.

```js
var unique = {};
var distinct = [];
for( var i in array ){
 if( typeof(unique[array[i].normal]) == "undefined"){
  distinct.push(array[i].normal);
 }
 unique[array[i].age] = 0;
}
```
