### ISSUE TITLE
derequire missing from the dependencies

### ISSUE THREAD

**Issue by ithil** [nlp-compromise/nlp_compromise#286]
Hey,
When I run `npm run build` I get the following error:

    Running "run:build" (run) task
    /bin/sh: derequire: command not found
    Warning: non-zero exit code 127 Use --force to continue.

Apparently `derequire` is missing from the `devDependencies`. After installing it everything worked. :)

**Comment by spencermountain** [comment]
yikes!
fixed it. 
thanks!
