### ISSUE TITLE
TypeError: nlp.text is not a function in 6.52

### ISSUE THREAD

**Issue by claudiorodriguez** [nlp-compromise/nlp_compromise#288]
Hello there! Version 6.5.1 works just fine, but version 6.5.2 throws this error:
`TypeError: nlp.text is not a function`
I version-locked for the time being but thought I'd give you a heads-up

**Comment by spencermountain** [comment]
ahhh! whaaa!
thanks for the heads-up!

**Comment by spencermountain** [comment]
oof, :sweat: 
fixed.
