### ISSUE TITLE
Last name tagging in v7

### ISSUE THREAD

**Issue by kahwee** [nlp-compromise/nlp_compromise#297]
Issue in v7, last names no longer appear to be surfaced. I think @spencermountain mentioned there is a helper for this in future for multipart words for dates so I'm not sure if this counts as a regression.

Anyhow, if I do this:

```js
console.log(nlp('my name is john smith').terms.map((term) => {
  return {
    text: term._text,
    tag: term.tag
  }
}))
```
I got this in return:

```js
[ { text: 'my',
    tag: { Possessive: true, NounPhrase: true, Noun: true } },
  { text: 'name', tag: { Noun: true, NounPhrase: true } },
  { text: 'is',
    tag: { Copula: true, Verb: true, VerbPhrase: true } },
  { text: 'john',
    tag:
     { MaleName: true,
       NounPhrase: true,
       Noun: true,
       Singular: true,
       Person: true,
       FirstName: true } },
  { text: 'smith', tag: { Verb: true, VerbPhrase: true } } ]
```

Also,

```js
console.log(nlp('my name is john smith').match('#Person').plaintext())
```

is returned with `john`, I'm expecting `john smith`.

**Comment by spencermountain** [comment]
hey, yeah this works a bit better now on branch/v7. Lastname is tricky.
right now, if it is titlecased, or passes right through the tagger unknown, it will become a lastname - but that's far from ideal still

**Comment by spencermountain** [comment]
It needs some fancy ideas, you up for it?
https://github.com/nlp-compromise/nlp_compromise/blob/v7/src/result/tag/corrections/index.js#L90

**Comment by kahwee** [comment]
That's cool. Thanks @spencermountain. How do we add new first names now.

Interestingly, in Chinese names, it's a lot easier to guess by family names, it tends to be "Tan", "Chen", "Gong", "Li", "Lee", "Ang", "Chan", "Liu", "Low". The format is typically FamilyName GivenName (LastName FirstName).

**Comment by spencermountain** [comment]
right. I understand it's similar in india - that lastname collision is really high.
maybe we should whitelist a couple hundred?

that way we could work backwards on some, and get firstnames we don't know

**Comment by spencermountain** [comment]
hey, i started-in on this. lots to do still
https://github.com/nlp-compromise/nlp_compromise/blob/v7/src/data/people/lastnames.js#L1

**Comment by spencermountain** [comment]
hey so I understand polish last names are `.ski$` for men, and `.ska$` for women.
if you, or anybody is good with this stuff, i wanna throw them all in. it's not my expertise.

**Comment by spencermountain** [comment]
gonna merge this with #169
