### ISSUE TITLE
toNumber() doesn't work as expected in 7.0.0-alpha3

### ISSUE THREAD

**Issue by benhjames** [nlp-compromise/nlp_compromise#301]
This behaviour has started happening in 7.0.0-alpha3:

```js
const nlp = require('nlp_compromise');
const test = nlp('test one okay').values().toNumber().plaintext();
console.log(test);
// ' 1'
```

I expected to get `test 1 okay` but actually got ` 1`.

Perhaps I'm using the new API incorrectly (which is awesome btw) - do let me know! :smile:

**Comment by spencermountain** [comment]
hey thanks ben!
yeah, i've been monkeying around with it today/yesterday on the v7 branch.
so `.values()` should find a subset ('one') and to 'zoom out' you can do `.all()`
```javascript
 nlp('test one okay').values().toNumber().all().plaintext();
```
alternatively, it's mutable, so:
```javascript
var m= nlp('test one okay')
m.values().toNumber()
m.plaintext();
```
if that doesn't work, lemme know and I'll fix it today
cheers

**Comment by benhjames** [comment]
Nice one, both those work great - cheers!
