### ISSUE TITLE
'arise' as a verb gets clobbered by suffix generation

### ISSUE THREAD

**Issue by TSavo** [nlp-compromise/nlp_compromise#305]
I'm trying to add 'arise' as an irregular verb, but no matter what I do, the suffixes supplied always get clobbered by the suffix rule generator.

Specifically I'm adding the following to irregular_verbs.js:

```
arise: {
    PresentTense: 'arise',
    PastTense: 'arose',
    Participle: 'arisen',
    Gerund: 'arising'
  },
```

And to verbs.js
```
  'arise',
```

And it's picking it up ok, but then when we conjugate the verb, but then on line 39 of /src/term/verb/conjugate/index.js the values are overwritten by the suffixPass:

```
all = Object.assign(all, suffixPass(inf));
```

Before:
```
all = Object {PastTense: "arose", PresentTense: "arise", FutureTense: null, Infinitive: "arise", Gerund: "arising"…}
```

After:
```
all = Object {PastTense: "arised", PresentTense: "arises", FutureTense: null, Infinitive: "arise", Gerund: "arising"…}
```

Any idea what I'm doing wrong here?

**Comment by spencermountain** [comment]
agh, that's a good find.
yeah, the suffix rules should never overwrite the given irregulars. i'll check it out today

**Comment by spencermountain** [comment]
hey, yeah you are right. swapping the Obj.assign parameters fixes it, but fails some tests.
i'll push a release once they're fixed

**Comment by spencermountain** [comment]
hey, got it.
`npm i nlp_compromise@next`
```javascript

let m = nlp('arise').tag('Verb');
console.log(m.verbs().conjugate());
/*[ { PastTense: 'arose',
    PresentTense: 'arises',
    FutureTense: 'will arise',
    Infinitive: 'arise',
    Gerund: 'arising',
    Actor: 'ariser',
    PerfectTense: 'have arisen',
    Pluperfect: 'had arose',
    Participle: 'arisen',
    Adjective: 'ariseable' } ]
*/
```
cheers
