### ISSUE TITLE
Stick with "compromise" variable name throughout examples

### ISSUE THREAD

**Issue by giorgio79** [nlp-compromise/nlp_compromise#486]
Wonder why the compromise var is named as nlp? :) 
```
var nlp = require('compromise')

var doc = nlp('London is calling')
doc.sentences().toNegative()
```

Why not keep it as compromise?

var compromise = require('compromise')

var doc = compromise('London is calling')
doc.sentences().toNegative()

Like Natural is sticking to its namespace https://github.com/NaturalNode/natural

`var natural = require('natural');`

**Comment by spencermountain** [comment]
hey György, yeah it's weird. it would be a bad breaking change to fix it,
it's exported like that for the browser, so that's why I used that name in the docs. You can call it anything you'd like in your nodejs app.
cheers
