### ISSUE TITLE
Verb Tense Bug in Demo

### ISSUE THREAD

**Issue by mjhasbach** [nlp-compromise/nlp_compromise#60]
Sentence:

> joe carter plays patiently in toronto

Steps to reproduce:

1. Change plays to past-tense
2. Negate played

Result:

> joe carter didn't **playe** patiently in toronto

**Comment by spencermountain** [comment]
ah! thanks. yeah, this to_negative -> to_negative needs some attention. Let me take a look. Thanks Matthew

**Comment by spencermountain** [comment]
hey Matthew, I finally got to this in `v6.4.6`.
```javascript
console.log(nlp.text('joe carter plays patiently in toronto').to_past().negate().text());
//joe carter didn't play patiently in toronto
```
cheers
