### ISSUE TITLE
past tense '-dy', '-ly'  

### ISSUE THREAD

**Issue by mcelliott** [nlp-compromise/nlp_compromise#65]
I think maybe this is not working correctly, but as it seems broken for a bunch of verbs, maybe I'm missing something...

    nlp.verb('study').to_past()
    "studyed"

    nlp.verb('apply').to_past()
    "applyed"

**Comment by spencermountain** [comment]
thanks matt, you're right. This part is goofed-up.
I'm re-doing this method in the [2.0 branch](https://github.com/spencermountain/nlp_compromise/tree/2.0), which is a few weeks away still. I'll make sure this issue gets addressed there. It looks like just a regex goof-up.
Will let you know, thanks.

**Comment by mcelliott** [comment]
:+1:

**Comment by ilyankou** [comment]
I can't believe it's been hanging here for months – easy fix! Waiting to be merged.

**Comment by spencermountain** [comment]
🎉  🎆   🎉   🎉 !
