### ISSUE TITLE
nlp.sentences() collapses whitespace

### ISSUE THREAD

**Issue by rbhalla** [nlp-compromise/nlp_compromise#67]
Pretty self explanatory, but if there are multiple white space characters between a word, the sentence detected collapses these characters together

**Comment by spencermountain** [comment]
hi Roshan, this is a good point.
I'm not sure the best way to fix this though. Out of curiosity, what's your use-case where non-grammatical white-space needs to be preserved? I'd be happy to bake something into this new version we're working on.
cheers

**Comment by rbhalla** [comment]
I essentially have a block of text with certain keywords I want to detect. For each keyword I want to also highlight the sentence it was mentioned in.

Now technically, the sentence returned isn't actually present in the original block of text, so being able to modify the original block of text to wrap certain sentences in tags isn't trivial. I'm getting around it using some very brittle fuzzy searching, but I'm not entirely sure I've covered all edge cases. Ideally I'd be able to use the returned sentence and immediately find and replace it in the original text.

That might not read well, so let me know if I need to clarify on it.

Also have to mention this is a great library and I appreciate you responding so quickly!

**Comment by spencermountain** [comment]
;) thanks!
that makes a lot of sense. I will add a raw_text field to sentence today, for the new version in about a month. I'll let you know. Thanks for the compliments.
-spence

**Comment by rbhalla** [comment]
Perfect, thanks. If this is on the roadmap feel free to close this issue or keep it as a reminder. I'll be watching the repo for any updates

**Comment by nealrs** [comment]
replace is still kind of broken (unless it doesn't work for adjectives):

```javascript
nlp.sentence('My cat is brown').replace('the [Adjective]', 'orange').text()
```
throws:
```
/Users/neal/Desktop/nlp/node_modules/nlp_compromise/builds/nlp_compromise.js:2166
  list.forEach(function (t) {
      ^

TypeError: Cannot read property 'forEach' of null
    at Object.replaceAll (/Users/neal/Desktop/nlp/node_modules/nlp_compromise/builds/nlp_compromise.js:2166:7)
    at Sentence.replace (/Users/neal/Desktop/nlp/node_modules/nlp_compromise/builds/nlp_compromise.js:3970:14)
```

**Comment by spencermountain** [comment]
oof, thanks Neal. These examples do i think, what you're trying to do: 
```javascript
nlp.sentence('My cat is brown').match('is [Adjective]')[0].text();
//is brown
nlp.sentence('My cat is brown').replace('is [Adjective]', 'is orange').text();
//My cat is orange
```

Yeah, there's some big problems though, regarding 1-1 tokenization of the search and replace strings. That's not a very nice error, and it exposes some tricky, big stuff.

@rbhalla amusingly, I think I fixed your issue and forgot to tell you. Check out [the tests](https://github.com/nlp-compromise/nlp_compromise/blob/master/test/unit_tests/sentence/whitespace.js) that all return pixel-perfect whitespace from the `.text()` method. Is that helpful?
cheers

**Comment by rbhalla** [comment]
Hi @spencermountain that seems right, but when testing I came across this:

`nlp.text('This is a test.   This is another   sentence.').sentences;`

Gives me the two sentences:
`'This is a test.   '`
`'This is another   sentence.'`

Is the first sentence desired behaviour?

**Comment by spencermountain** [comment]
hi Roshan, yeah I believe this is the least-awkward of all results. Let me know if you have any proposals for an alternative syntax. cheers!
