### ISSUE TITLE
Adjectives tagged as verbs due to "adjective-after-pronoun"

### ISSUE THREAD

**Issue by gregweston** [nlp-compromise/nlp_compromise#71]
If a question such as "Are you real?" is broken down into tags, the library will tag "real" as a verb. This appears to be due to lines 199 - 202 in /src/pos.js, where adjectives are tagged as verbs if the previous token was a pronoun. Not 100% sure but I think this rule should only apply if the adjective in question doubles as a past participle like "gone", "done", "lost", etc.

**Comment by spencermountain** [comment]
ahh, very interesting. thanks greg.
I'm working really hard on a v2.0, and it has just begun conjugating to past participle - a subject I haven't really gotten my head around yet. It makes sense, the way you've described it, as verbs that turn into adjectives - how many do you think there are? Maybe it's something we could handle properly in some kind of list.

In your example, I think I killed that rule in v2, but these kind of question sentences should be properly supported. 
I'll leave this open, and make sure it gets resolved somehow in v2. if you wanna jump in, it's [here](https://github.com/spencermountain/nlp_compromise/tree/2.0)
cheers

**Comment by ilyankou** [comment]
It seems to be working as desired (real, gone, done are marked adjectives). @spencermountain close the issue?

**Comment by spencermountain** [comment]
thanks!
