### ISSUE TITLE
Places not working

### ISSUE THREAD

**Issue by liuzzi** [nlp-compromise/nlp_compromise#83]
Hey guys, cool library...I can't seem to get the places recognition working.   Is there a more general getNamedEntities or something of the such?

Im trying like this:
nlp_compromise.text('I live in Boston').places()   and it returns empty in every trial I can think of

Thanks!

**Comment by spencermountain** [comment]
hey Frankie, this may be an unfortunate coincidence, "Boston" is an especially ambiguous term because the band, and the play etc. You can see the list of less-ambiguous city names [here](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/data/places.js#L179)
