### ISSUE TITLE
README example tense is wrong

### ISSUE THREAD

**Issue by dbkaplun** [nlp-compromise/nlp_compromise#85]
```js
nlp.text("She sells seashells").negate()
// She didn't sell seashells
```
should be:
```js
nlp.text("She sells seashells").negate()
// She doesn't sell seashells
```
or:
```js
nlp.text("She sells seashells").negate()
// She isn't selling seashells
```

**Comment by spencermountain** [comment]
that's a good point.

**Comment by spencermountain** [comment]
so the logic is [this](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/sentence/negate.js#L94) - 

[past tense] - "sold" -> "didn't sell"
[present] - "sells" -> "doesn't sell"
[future] - "will sell" -> "won't sell"

it may just be that the readme is wrong. I'll take a look this afternoon.

**Comment by spencermountain** [comment]
got it. thanks!
