### ISSUE TITLE
Improve usage instructions for novices

### ISSUE THREAD

**Issue by julianpeeters** [nlp-compromise/nlp_compromise#86]
Love this project, but I no longer understand how to use it in my simple app. I used to simply add a script tag to my html:

`<script type="text/javascript" src="https://rawgit.com/spencermountain/nlp_compromise/master/client_side/nlp.min.js"> </script>`

But for the new version, I'm not yet familiar with node and npm. Where should I install the module, inside my project or outside of it?

I tried `npm install nlp_compromise`, then copied `nlp_compromise.es5.min.js` into my project, and adjusted the recommended `<script src="./builds/nlp_compromise.es5.min.js"> </script>` to point to it.

But that got me an error: 

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create nlp_compromise.es5.min.js:5:11112
TypeError: a.match is not a function
 nlp_compromise.es5.min.js:5:5697` 

What am I missing? Thanks

**Comment by spencermountain** [comment]
hi Julian, thanks for the kind words, and sorry for the delay.
I completely agree, I've done some big changes the past few weeks and the documentation & build have suffered.
That prototype thing sounds like a crazy bug with the build process. give me a few days, I'll try to turn it around.
that rawgit cdn is a little goofy, and i nominated this project on cdnjs, and haven't heard anything. The best way to get a cdn going is probably just do put it on an amazon cdn myself. I should probably do this.

**Comment by julianpeeters** [comment]
Ok sounds great.

**Comment by spencermountain** [comment]
hey, how's this?
https://github.com/nlp-compromise/nlp_compromise/blob/master/demo/index.html

view it at:
http://rawgit.com/nlp-compromise/nlp_compromise/master/demo/index.html

**Comment by julianpeeters** [comment]
The dependency is now available for me again (at `http://rawgit.com/nlp-compromise/nlp_compromise/master/builds/nlp-compromise.es5.min.js`), but I still get the error:

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create nlp-compromise.es5.min.js:5:11112
TypeError: a.match is not a function`

Any ideas? I'm using it with Scala.js and building with sbt, which was working before the recent changes.

Thanks for the efforts, no rush!

**Comment by spencermountain** [comment]
hey Julian, think this is working now.
i [don't see](http://rawgit.com/nlp-compromise/nlp_compromise/master/demo/simple_demo.html) any errors when i load the [simple demo](https://github.com/nlp-compromise/nlp_compromise/blob/master/demo/simple_demo.html)
I have seen issues like this with webpack, various compilers/loaders. Please re-open this issue if it persists. cheers
