### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by DigitalSkyline** [nlp-compromise/nlp_compromise#95]
{
"text": "cost of",
"normal": "cost of",
"implicit": "",
"reason": "phrasal(lexicon_pass)",
"pos": {
"Verb": true,
"Infinitive": true
},
"tag": "Infinitive",
"conjugations": {
"past": "cost of of of of",
"infinitive": "cost of of of of",
"gerund": "costing of of of of",
"actor": "coster of of of of",
"present": "costs of of of of",
"future": "will cost of of of of",
"perfect": "have cost of of of of",
"pluperfect": "had cost of of of of",
"future_perfect": "will have cost of of of of"
}
}

**Comment by spencermountain** [comment]
ahh! will take a look.
thanks paul.

**Comment by DigitalSkyline** [comment]
Seems to be doing it here as well:

{
"text": "wrote about",
"normal": "wrote about",
"implicit": "",
"reason": "phrasal(lexicon_pass)",
"pos": {
"Verb": true,
"PastTense": true
},
"tag": "PastTense",
"conjugations": {
"gerund": "writing about about about about about about",
"past": "wrote about about about about about about",
"infinitive": "write about about about about about about",
"actor": "writer about about about about about about",
"present": "writes about about about about about about",
"future": "will write about about about about about about",
"perfect": "have wrote about about about about about about",
"pluperfect": "had wrote about about about about about about",
"future_perfect": "will have wrote about about about about about about"
}
},

**Comment by spencermountain** [comment]
ah, got it.
will update in 3.0.3
thanks man.
